apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edv-service.fullname" . }}
  labels:
    {{- include "edv-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJpdmZwYWNyLmF6dXJlY3IuaW8iOiB7CgkJCSJhdXRoIjogImFYWm1jRUZqY2pwSlJqMDJURVkxWkZJNFpuZFBNVUV2V1ROR1Jtd3pha0ZYY1U4NFZXVnRjUT09IgoJCX0KCX0KfQo=
